---
deployment:
  tasks:
    - export DEPLOYPATH=/home/beelkstc/interventie.org
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R api.php $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
